### PR TITLE
Add Tidyverse example to EN notebook

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
@katilp, @andrewjohnlowe: I've updated the EN notebook (only, no PDF yet), based on #3. Could you take it for a spin and let me know if this is good to go?

## TODO

- [x] @katilp approves inclusion of Tidyverse example at end of notebook: [Try it here](https://mybinder.org/v2/gh/RaoOfPhysics/cms-rmaterial-multiple-languages/add-tidyverse?filepath=EN-R-tutorial.ipynb)
- [x] @andrewjohnlowe approves code and explanation: [Try it here](https://mybinder.org/v2/gh/RaoOfPhysics/cms-rmaterial-multiple-languages/add-tidyverse?filepath=EN-R-tutorial.ipynb)
- [x] @RaoOfPhysics generates PDF and pushes to this PR

### CODE REVIEW

**Comment by katilp** [comment]
Thanks, looks very nice! I've learned something new again 😄 
As a small detail, take note that in the text at the beginning there are quite a many terms, which may scare away dummies like me 😃 "tidyverse", "dockerfile", "binder", "repo"... I may have heard about R but I do not know what tidyverse is (or did not know when I started to read, then I learned, but I may have stopped reading during the first lines...). Maybe just move to the end? Or say few words about it (as already done at the end), but remember the target audience

"N.B.: Original text and code by Edith Villegas Garcia. Code using tidyverse instead of base R by Andrew John Lowe. Edited and converted to a Jupyter notebook by Achintya Rao.

This notebook can be run in Binder by following the instructions from https://github.com/binder-examples/dockerfile-r. In addition to the packages installed by the example Dockerfile there, tidyverse is also installed for this repo."

**Comment by RaoOfPhysics** [comment]
@katilp: Very good points. I got sucked into jargon, which is poor form. I'll clean it up and submit some changes tomorrow or on Friday.

**Comment by RaoOfPhysics** [comment]
@katilp, this text…

> N.B.: Original text and code by Edith Villegas Garcia. Code using tidyverse instead of base R by Andrew John Lowe. Edited and converted to a Jupyter notebook by Achintya Rao.
>
> This notebook can be run in Binder by following the instructions from https://github.com/binder-examples/dockerfile-r. In addition to the packages installed by the example Dockerfile there, tidyverse is also installed for this repo.

is now changed to…

> N.B.: Original text and code by Edith Villegas Garcia, with additions by Andrew John Lowe. Edited and converted to this interactive notebook by Achintya Rao.

And the technical info has been moved to the [README](https://github.com/RaoOfPhysics/cms-rmaterial-multiple-languages/blob/add-tidyverse/README.md):

> ## Technical information
>
> You can use [Binder](https://mybinder.org) to interact with any such notebook via a browser without installing Jupyter or R, by hosting your notebooks on GitHub.
> To do so, make sure that your GitHub repository contains the Dockerfile shown here: [https://github.com/binder-examples/dockerfile-r](https://github.com/binder-examples/dockerfile-r).
> Install any additional packages you want to interact with (e.g. `tidyverse`) by including them in the Dockerfile.

Hope this is better?

**Comment by katilp** [comment]
Perfect, thanks a lot!

**Comment by DrAndiLowe** [comment]
Looks good to me! A small point: the slight change of x-axis title ("GeV" → "GeV/c²") was merely to demonstrate to users that they can include math expressions that will be rendered appropriately. I don't mind that this change wasn't kept.

**Comment by DrAndiLowe** [comment]
P.S. I suppose I could have provided a vectorised implementation of the invariant mass calculation, but it's only marginally more succinct because there's no package for representing 4-vectors. I looked. Don't know if it's worth making a wrapper for CLHEP.

**Comment by RaoOfPhysics** [comment]
Thanks, @andrewjohnlowe!

> A small point: the slight change of x-axis title ("GeV" → "GeV/c²") was merely to demonstrate to users that they can include math expressions that will be rendered appropriately.

Yes, I considered keeping it but didn't want to confuse the reader by showing both GeV and GeV/c² in different places for the same thing. :)

> I suppose I could have provided a vectorised implementation of the invariant mass calculation…

I think the current way of analysing the data is suitable the the scope of this tutorial. :)

Thanks, once again!

**Pull request merged**
