### PR TITLE
Add Jupyter notebook for EN analysis example

### PR DESCRIPTION
**Pull request by RaoOfPhysics**

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
@katilp: Please see https://mybinder.org/v2/gh/RaoOfPhysics/cms-rmaterial-multiple-languages/add-jupyter-notebook?filepath=EN-R-tutorial.ipynb for Binder support.

Can you test everything and let me know if it works?

If so, I'll move the PDFs to a separate directory, add a meaningful README and potentially a LICENSE too.

**Comment by katilp** [comment]
I did not make it time to test yet, I'll do asap. 
But would however it make sense to keep the pdf's in that directory as well?
They should do no harm and could be convenient for people having a running R environment other than a notebook (I know... we do not do this for python examples either but.....)

**Comment by RaoOfPhysics** [comment]
@katilp: Sure, that would work. However, is it possible for me to get the file that generated the PDF so I can fix some small things in it before we share it on the COD portal?

**Comment by katilp** [comment]
Sure, try contact edith: @edithvillegas

**Comment by RaoOfPhysics** [comment]
Updated and tested! Looks good for merging. :)

**Pull request merged**
